# Generated by Django 4.0.4 on 2022-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_public',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of public'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
