# Generated by Django 4.0.4 on 2022-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_articles_options_alter_articles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
