# Generated by Django 4.0.4 on 2022-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_articles_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(upload_to='photos', verbose_name='Photo'),
        ),
    ]
