version: "3.3"

services:
  postgres:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432:5432


  web:
    build:
      context: news_site
      dockerfile: Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./news_site/:/news_site/
      - static_volume:/news_site/static
      - media_volume:/news_site/media
    env_file:
      - .env.dev
    depends_on:
      - postgres

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/news_site/static
      - media_volume:/news_site/media
      - react_volume:/react_front
    ports:
      - 1337:80
    depends_on:
      - web

  frontend:
    build:
      context: react_front
      dockerfile: Dockerfile
    command: [ "npm", "start" ]
    volumes:
      - ./react_front/:/react_front/
      - react_volume:/react_front
#      - node-modules:/app/react_front/node_modules
    expose:
      - 3000

  liquibase:
    build:
     context: liquibase
     dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
     - 8001:8001



volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_volume:





